name: Release Rust Program

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the Rust project
        run: |
          cargo build --release

      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: rust-binary
          path: target/release/mydict
